<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVANeWXU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVANeWXU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVANeWXU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVANeWXU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVANeWXU\App_KernelDevDebugContainer([
    'container.build_hash' => 'VANeWXU',
    'container.build_id' => '21e93ba7',
    'container.build_time' => 1678653463,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVANeWXU');
