<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_first' => [[], ['_controller' => 'App\\Controller\\FirstController::index'], [], [['text', '/first']], [], [], []],
    'say.hello' => [['name', 'firstname'], ['_controller' => 'App\\Controller\\FirstController::sayHello'], [], [['variable', '/', '[^/]++', 'firstname', true], ['variable', '/', '[^/]++', 'name', true], ['text', '/sayHello']], [], [], []],
    'multiplication' => [['entier1', 'entier2'], ['_controller' => 'App\\Controller\\FirstController::multiplication'], ['entier2' => '\\d+', 'entier1' => '\\d+'], [['variable', '/', '\\d+', 'entier2', true], ['variable', '/', '\\d+', 'entier1', true], ['text', '/multi']], [], [], []],
    'session' => [[], ['_controller' => 'App\\Controller\\SessionController::index'], [], [['text', '/session']], [], [], []],
    'todo' => [[], ['_controller' => 'App\\Controller\\TodoController::index'], [], [['text', '/todo/']], [], [], []],
    'todo.add' => [['name', 'content'], ['content' => 'sf6', 'name' => 'samedi', '_controller' => 'App\\Controller\\TodoController::addTodo'], [], [['variable', '/', '[^/]++', 'content', true], ['variable', '/', '[^/]++', 'name', true], ['text', '/todo/add']], [], [], []],
    'todo.update' => [['name', 'content'], ['_controller' => 'App\\Controller\\TodoController::updateTodo'], [], [['variable', '/', '[^/]++', 'content', true], ['variable', '/', '[^/]++', 'name', true], ['text', '/todo/update']], [], [], []],
    'todo.delete' => [['name'], ['_controller' => 'App\\Controller\\TodoController::deleteTodo'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/todo/delete']], [], [], []],
    'todo.reset' => [[], ['_controller' => 'App\\Controller\\TodoController::resetTodo'], [], [['text', '/todo/reset']], [], [], []],
];
